apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: realtime-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: fake.flyzipeline.com
    http:
      paths:
      - path: /
        backend:
          serviceName: realtime
          servicePort: 80